theme: jekyll-theme-minimal
title: Statistics and Modeling (STA-371G) Spring 2019
description: This is the course website for all sections of Prof. Jared Murray's Statistics and Modeling (STA-371G) course.
show_downloads: "false"
classyear: spring 2019